apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cricket-api-hpa
  labels:
    app: cricket-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cricket-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
